# Generated by Django 4.1.1 on 2022-12-01 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('al', '0003_alter_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=50, null='True'),
            preserve_default='True',
        ),
    ]
